{% set name = "simpeg-drivers" %}
{% set version = "0.2.0a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/MiraGeoscience/simpeg/archive/v0.19.0.8+mira.tar.gz
  # sha256: f48e21e1e3d1df79be0baad2bc0b91f83714ddf53780a6849f9a60f9418a735b
  path: ../{{ name }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10, <3.11
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >=3.10,<3.11
    - dask-core 2024.06.*
    - discretize >=0.10.0,<0.11.0
    - distributed >=2024.06.*
    - numpy >=1.26.0,<1.27.0
    - scipy >=1.14.0,<1.15.0
    - geoh5py >=0.10.0a0.dev0,<0.11.0
    - octree-creation-app >=0.2.0a0.dev0,<0.3.0
    - geoapps-utils >=0.4.0a0.dev0,<0.5.0
    - mira-simpeg >=0.21.2.1a0.dev0,<0.22.0
    - param-sweeps >=0.1.8a0.dev0,<0.1.9
    - pillow >=10.3.0
    - empymod >=2.2.1,<2.3.0
    - geoana >=0.5.0,<0.6.0
    - h5py >=3.2.1,<4.0.0
    - matplotlib-base >=3.8.4,<3.9.0
    - mkl >=2023.2, <2023.3
    - pandas >=2.2.1,<2.3.0
    - pydantic >=2.5.2,<3.0.0
    - pydiso >=0.0.5,<0.1.0
    - pymatsolver >=0.2.0,<0.3.0
    - scikit-learn >=1.4.0,<1.5.0
    - tqdm >=4.66.1,<5.0.0 
    - zarr >=2.14.2,<2.15.0
  run_constrained:
    - tbb 2021.12.*
    - tzdata 2023.4.*

test:
  imports:
    - SimPEG
  commands:
    - pip check
  requires:
    - pip

about:
  license: MIT
  license_file: 
    - LICENSE

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg