[build-system]
build-backend = 'poetry.core.masonry.api'
requires = ['poetry-core>=1.0.0', 'setuptools']

[tool]
[tool.conda-lock]
channels = ['conda-forge']
platforms = ['win-64', 'linux-64']

[tool.conda-lock.dependencies]
empymod = '>=2.2.1, <2.3.0'
fsspec = '2022.*'
geoana = '>=0.5.0, <0.6.0'
h5py = '>=3.2.1, <4.0.0'
libblas = '*=*mkl'
matplotlib-base = '>=3.8.4, <3.9.0'
mkl = '>=2023.2, <2023.3'
pandas = '>=2.2.1, <2.3.0'
pillow = '>=10.3.0, <10.4.0'
pydantic = '>=2.5.2, <3.0.0'
pydiso = '>=0.0.5, <0.1.0'
pymatsolver = '>=0.2.0, <0.3.0'
python-tzdata = '2023.4.*'
scikit-learn = '>=1.4.0, <1.5.0'
tbb = '2021.12.*'
tqdm = '>=4.66.1, <5.0.0'
zarr = '>=2.14.2, <2.15.0'

[tool.coverage]
[tool.coverage.html]
skip_covered = true
skip_empty = true

[tool.coverage.report]
exclude_lines = ['raise NotImplementedError', 'pass', 'if TYPE_CHECKING', 'pragma: no cover']
fail_under = 90

[tool.coverage.run]
branch = true
source = ['simpeg_drivers']

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
plugins = ['numpy.typing.mypy_plugin']
scripts_are_modules = true
show_column_numbers = true
show_error_context = true
warn_unused_configs = true

[tool.poetry]
authors = ['Mira Geoscience <support@mirageoscience.com>']
description = 'Application to run SimPEG inversions with geoh5 files from Geoscience Analyst.'
documentation = 'https://mirageoscience-simpeg-drivers.readthedocs-hosted.com/'
homepage = 'https://www.mirageoscience.com/mining-industry-software/python-integration/'
license = 'MIT'
maintainers = ['Benjamin Kary <benjamink@mirageoscience.com>', 'Dominique Fournier <dominiquef@mirageoscience.com>']
name = 'simpeg-drivers'
repository = 'https://github.com/MiraGeoscience/simpeg-drivers'
version = '0.2.0-alpha.1'

[tool.poetry.dependencies]
discretize = '~0.10.0'
distributed = '2024.6.*'
numpy = '~1.26.0'
python = '^3.10, <3.11'
scipy = '~1.14.0'

[tool.poetry.dependencies.dask]
extras = ['distributed']
version = '2024.6.*'

[tool.poetry.dependencies.geoapps-utils]
allow-prereleases = true
version = '>=0.4.0a0.dev0, <0.5.0'

[tool.poetry.dependencies.geoh5py]
allow-prereleases = true
version = '>=0.10.0a0.dev0, <0.11.0'

[tool.poetry.dependencies.mira-simpeg]
allow-prereleases = true
version = '~0.21.2.1.dev25'

[tool.poetry.dependencies.octree-creation-app]
allow-prereleases = true
version = '>=0.2.0a0.dev0, <0.3.0'

[tool.poetry.dependencies.param-sweeps]
allow-prereleases = true
version = '>=0.2.0a0.dev0, <0.2.1'

[tool.poetry.group]
[tool.poetry.group.dev]
[tool.poetry.group.dev.dependencies]
ipywidgets = '^7.6.5'
jupyter-book = '^0.14'
jupytext = '^1.14'
nbconvert = '~7.16.4'
pygments = '*'
pylint = '*'
pytest = '*'
pytest-cov = '*'
readthedocs-sphinx-ext = '*'
sphinx = '^5.0'
tomli = '*'

[[tool.poetry.include]]
format = ['sdist', 'wheel']
path = 'COPYING'

[[tool.poetry.include]]
format = ['sdist', 'wheel']
path = 'COPYING.LESSER'

[[tool.poetry.include]]
format = ['sdist', 'wheel']
path = 'LICENSE'

[[tool.poetry.include]]
format = ['sdist', 'wheel']
path = 'README.rst'

[[tool.poetry.include]]
format = ['sdist', 'wheel']
path = 'THIRD_PARTY_SOFTWARE.rst'

[[tool.poetry.include]]
format = ['sdist', 'wheel']
path = 'docs/**/THIRD_PARTY_SOFTWARE.rst'

[[tool.poetry.packages]]
include = 'simpeg_drivers'

[[tool.poetry.packages]]
include = 'simpeg_drivers-assets'

[[tool.poetry.source]]
name = 'jfrog-server'
url = 'https://mirageoscienceltd.jfrog.io/artifactory/api/pypi/public-pypi-dev/simple'

[tool.ruff]
target-version = 'py310'

[tool.ruff.lint]
ignore = ['B028', 'E501', 'F401', 'RUF005', 'RUF012']
select = ['A', 'B', 'B006', 'B9', 'BLE', 'C4', 'C9', 'E', 'F', 'I', 'RUF', 'TID', 'UP', 'W']

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.lint.mccabe]
max-complexity = 18
