schema_version: 1

context:
  name: "simpeg-drivers"
  version: "0.4.0a1"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ../${{ name }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.10.*
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    # Mira packages
    - geoapps-utils >=0.6.0a1, <0.7.dev
    - geoh5py >=0.12.0a1, <0.13.dev
    - mira-simpeg >=0.23.0.1a3, <0.23.1.dev
    - octree-creation-app >=0.4.0a1, <0.5.dev
    - param-sweeps >=0.3.0a1, <0.4.dev

    # direct dependencies
    - dask-core >=2025.3, <2025.4.dev
    - discretize >=0.11.0, <0.12.dev
    - distributed >=2025.3, <2025.4.dev
    - numpy >=1.26.0, <1.27.dev
    - pydantic >=2.5.2, <3.0.dev
    - pydiso >=0.1.0, <0.2.dev
    - python-mumps >=0.0.3, <0.0.4.dev
    - scikit-learn >=1.4.0, <1.5.dev
    - scipy >=1.14.0, <1.15.dev
    - tqdm >=4.66.1, <5.0.dev
    # constrain version for some indirect dependencies from SimPEG
    - geoana >=0.7.0, <0.8.dev
    - matplotlib-base >=3.8.4, <3.9.dev
    - pymatsolver >=0.3.0, <0.4.dev
    - zarr >=2.14.2, <2.15.dev
  run_constraints:
    - __glibc >=2.17
    - bokeh >=3.6.0, <3.7.dev
    - fsspec >=2022.0

tests:
  - python:
      imports:
        - simpeg_drivers
        - simpeg
        - geoh5py
        - dask
        - distributed
      pip_check: true

  - script:
      - pytest --ignore=tests/version_test.py
    requirements:
      run:
        - pytest
    files:
      source:
        - tests/

about:
  license: MIT
  license_file: LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/simpeg-drivers
  documentation: https://mirageoscience-simpeg-drivers.readthedocs-hosted.com/

extra:
  recipe-maintainers:
    - andrewg-mira
    - domfournier
    - sebhmg
