# '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#  Copyright (c) 2023-2026 Mira Geoscience Ltd.                                          '
#                                                                                   '
#  This file is part of simpeg-drivers package.                                     '
#                                                                                   '
#  simpeg-drivers is distributed under the terms and conditions of the MIT License  '
#  (see LICENSE file at the root of this source code package).                      '
#                                                                                   '
# '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
import shutil
from pathlib import Path

import numpy as np
import pytest
from geoapps_utils.utils.importing import GeoAppsError
from geoapps_utils.utils.transformations import rotate_xyz
from geoh5py import Workspace
from geoh5py.groups import PropertyGroup, SimPEGGroup
from geoh5py.objects import Points
from geoh5py.ui_json import InputFile

from simpeg_drivers import assets_path
from simpeg_drivers.electromagnetics.time_domain.driver import TDEMForwardDriver
from simpeg_drivers.electromagnetics.time_domain.options import TDEMForwardOptions
from simpeg_drivers.plate_simulation.driver import PlateSimulationDriver
from simpeg_drivers.plate_simulation.match.driver import PlateMatchDriver, fetch_survey
from simpeg_drivers.plate_simulation.match.options import PlateMatchOptions
from simpeg_drivers.plate_simulation.options import PlateSimulationOptions
from simpeg_drivers.utils.synthetics.driver import (
    SyntheticsComponents,
)
from simpeg_drivers.utils.synthetics.options import (
    MeshOptions,
    ModelOptions,
    SurveyOptions,
    SyntheticsComponentsOptions,
)
from tests.utils.targets import get_workspace


def generate_example(geoh5: Workspace, n_grid_points: int, refinement: tuple[int]):
    opts = SyntheticsComponentsOptions(
        method="airborne tdem",
        survey=SurveyOptions(
            n_stations=n_grid_points,
            n_lines=1,
            width=1000,
            drape=40.0,
            topography=lambda x, y: np.zeros(x.shape),
        ),
        mesh=MeshOptions(refinement=refinement),
        model=ModelOptions(background=0.001),
    )
    components = SyntheticsComponents(geoh5, options=opts)
    vals = components.survey.add_data(
        {"observed_data": {"values": np.random.randn(components.survey.n_vertices)}},
    )

    # Shift survey up (for single line)
    components.survey.vertices = components.survey.vertices + np.r_[0, 100, 0]
    components.property_group = PropertyGroup(components.survey, properties=vals)
    components.queries = Points.create(geoh5, vertices=np.random.randn(1, 3))

    return components


def test_file_parsing(tmp_path: Path):
    """
    Generate a few files and test the
    plate_simulation.match.Options.simulation_files() method.
    """
    filenames = [
        "sim_001.txt",
        "sim_002.txt",
        "sim_010.txt",
        "sim_011.txt",
    ]
    for fname in filenames:
        (tmp_path / fname).touch()

    with get_workspace(tmp_path / f"{__name__}.geoh5") as geoh5:
        components = generate_example(geoh5, n_grid_points=3, refinement=(2,))
        options = PlateMatchOptions(
            geoh5=geoh5,
            survey=components.survey,
            data=components.property_group,
            queries=components.queries,
            topography_object=components.topography,
            simulations=tmp_path,
        )

    sim_files = options.simulation_files
    assert len(sim_files) == 1
    assert sim_files[0].name == f"{__name__}.geoh5"

    with pytest.raises(GeoAppsError, match="No survey found under Plate Simulation"):
        PlateMatchDriver(options)

    # Copy the survey as if it was generated by the PlateSimulationDriver
    with geoh5.open():
        sim_group = SimPEGGroup.create(geoh5, name="Plate Simulation")
        survey = geoh5.get_entity("survey")[0]
        new_survey = survey.copy(parent=sim_group)
        metadata = survey.metadata
        metadata["EM Dataset"].pop("Channels")
        new_survey.metadata = metadata

    with pytest.raises(GeoAppsError, match="No time channels found in survey"):
        PlateMatchDriver(options)


def test_matching_driver(tmp_path: Path):
    """
    Generate a few files and test the
    plate_simulation.match.Options.simulation_files() method.
    """

    # Generate simulation files
    with get_workspace(tmp_path / f"{__name__}.geoh5") as geoh5:
        components = generate_example(geoh5, n_grid_points=32, refinement=(2,))

        params = TDEMForwardOptions.build(
            geoh5=geoh5,
            mesh=components.mesh,
            topography_object=components.topography,
            data_object=components.survey,
            starting_model=components.model,
            x_channel_bool=True,
            y_channel_bool=True,
            z_channel_bool=True,
        )

        fwr_driver = TDEMForwardDriver(params)

        ifile = InputFile.read_ui_json(
            assets_path() / "uijson" / "plate_simulation.ui.json", validate=False
        )
        ifile.data["geoh5"] = geoh5
        ifile.data["simulation"] = fwr_driver.out_group

        plate_options = PlateSimulationOptions.build(ifile.data)
        plate_options.model.overburden_model.thickness = 40.0
        plate_options.model.plate_model.dip_length = 300.0
        driver = PlateSimulationDriver(plate_options)
        driver.run()

    # Make copies of the generated simulation file to emulate a sweep
    file = tmp_path / f"{__name__}.geoh5"
    new_dir = tmp_path / "simulations"
    new_dir.mkdir(parents=True, exist_ok=True)

    for ii in range(1, 5):
        new_file = new_dir / (file.stem + f"_[{ii}].geoh5")
        shutil.copy(file, new_file)

        # Modify the data slightly
        with Workspace(new_file) as sim_geoh5:
            survey = fetch_survey(sim_geoh5)
            prop_group = survey.get_entity("Iteration_0_z")[0]
            scale = np.cos(np.linspace(-np.pi / ii, np.pi / ii, survey.n_vertices))

            for uid in prop_group.properties:
                child = survey.get_entity(uid)[0]
                child.values = child.values * scale

            # Downsample data
            mask = np.ones_like(child.values, dtype=bool)
            mask[1::2] = False
            survey.remove_vertices(mask)
            indices = np.arange(survey.n_vertices)
            survey.cells = np.c_[indices[:-1], indices[1:]]

    # Run the matching driver
    with geoh5.open():
        survey = fetch_survey(geoh5)

        # Rotate the survey to test matching
        survey.vertices = rotate_xyz(survey.vertices, [0, 0, 0], 215.0)

        # Flip the data to simulate up-dip measurements
        prop_group = survey.get_entity("Iteration_0_z")[0]
        for uid in prop_group.properties:
            child = survey.get_entity(uid)[0]
            child.values = child.values[::-1]

        # Change the strike angle to simulate a different orientation
        strikes = components.queries.add_data(
            {
                "strike": {
                    "values": np.full(components.queries.n_vertices, -10.0),
                }
            }
        )

        options = PlateMatchOptions(
            geoh5=geoh5,
            survey=survey,
            data=prop_group,
            queries=components.queries,
            strike_angles=strikes,
            topography_object=components.topography,
            simulations=new_dir,
        )
        match_driver = PlateMatchDriver(options)
        results = match_driver.run()

        assert isinstance(results, Points)

        names = results.get_data("file")[0]
        assert names.values[0] == file.stem + f"_[{4}].geoh5"

        assert geoh5.get_entity("Query [0]")[0].geometry.dip_direction == 45.0
