# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Simpeg-Drivers - Geophysical Inversion with ANALYST
logo: images/GA-Python_2.png
author: Mira Geoscience Ltd.
copyright: "2025"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  exclude_patterns: [case_studies/Forrestania/python_code/*,]
  run_in_temp: true

sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.intersphinx
    - sphinx.ext.todo
    - sphinx_issues
    - sphinxcontrib.googleanalytics
  local_extensions:
    dynamic_config: _ext/
  recursive_update: true
  config:
    project: simpeg-drivers
    html_static_path:
      - _static/custom.css
    html_theme: alabaster
    autodoc_typehints: signature
    autodoc_typehints_format: short
    suppress_warnings:
      - etoc.toctree
    intersphinx_mapping:
      # use None to auto‑fetch objects.inv
      numpy:
        - https://numpy.org/doc/1.26/
        - null
      python:
        - https://docs.python.org/3/
        - null
    todo_include_todos: true
    issues_github_path: mirageoscience/simpeg-drivers
    autodoc_type_aliases:
      np.ndarray: numpy.ndarray
      UUID: uuid.UUID

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

bibtex_reference_style:
  - author_year

repository:
  url: https://github.com/MiraGeoscience/simpeg-drivers
  path_to_book: docs
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
