name: geoh5py_docs

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scipy
  - numpy
  - h5py
  - dask
  - geoh5py
  - pydantic
  - simpeg
  - discretize
  - pip
  - ipykernel
  - jupyter-book
  - jupytext
  - notebook
  - zarr
  - pip:
    - colorcet
    - sphinx
    - matplotlib
    - pandas
    - sphinx_issues
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - sphinxcontrib-googleanalytics
    - nbsphinx
    - pillow
    - geoh5py
    - nbstripout
    - numpydoc
    - jupyter_client
