name: Dependabot auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-workflow-dependabot-auto-merge:
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-dependabot-auto-merge.yml@b2de1e00a0be160d8cf6e14716825673070bf264 # v3.13.0
    permissions:
      contents: write
      pull-requests: write
      statuses: write
      checks: read
    with:
      dependabot-groups: mirageo-ci-tools,pre-commit-hooks
      checks-to-skip: 'pre-commit.ci - pr,CodeQL'
