name: Create JIRA issue

on:
  issues:
    types: [opened]

permissions: {}

jobs:
  call-workflow-create-jira-issue:
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-jira-issue_to_jira.yml@b2de1e00a0be160d8cf6e14716825673070bf264 # v3.13.0
    permissions:
      contents: read
      issues: write
    with:
      project-key: 'GEOPY'
      components: '[{"name": "simpeg"}]'
    secrets:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN_WRITE }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL_WRITE }}
