name: WIP status

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]

jobs:
  call-workflow-wip-status:
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-wip-status.yml@b2de1e00a0be160d8cf6e14716825673070bf264 # v3.13.0
    permissions:
      contents: read
      statuses: write
